### ISSUE TITLE
DetailType case is not accurate

### ISSUE THREAD

**Issue by JSteunouSteeple** [event-catalog/generator-eventbridge#19]
### I tried this:

When using filters I had some difficulties because all my events are named using *snake_case* and at 1st nothing I tried worked.

Something like this in the config generate no events

```js
        services: [
          {
            id: 'foo', version: '1', sends: [{detailType: ['foo_bar_created']}],
          }

```

### This happened:

But using this config

```js
        services: [
          {
            id: 'foo', version: '1', sends: [{detailType: ['Foo_bar_created']}],
          }

```

make it work.

It appears the detail type is fetch using the event name splitted in parts. But the event name  is `source@DetailType` with detail type being transformed with a 1st capital letter.

I dont thing you should rely on this and rather fetch the true detail type property.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by boyney123** [comment]
Ah yeah makes sense.

To be honest, I wonder if we should just lowercase both when comparing? I can't think of time when you would want to define events by the case they are using?

**Comment by JSteunouSteeple** [comment]
Could work. Might introduce other issues I cannot think of right now because not a strict comparison so not my favorite though

**Comment by boyney123** [comment]
Yeah guess the other option is to get information for each event, which might slow down the generator to be honest.

I think stage 1 let's do a lowercase comparison, then if people have issues, we can reopen and explore other options too.

**Comment by boyney123** [comment]
Thanks @JSteunouSteeple ,

You can try `@eventcatalog/generator-eventbridge@1.2.4` this should fix the case issue

**Comment by JSteunouSteeple** [comment]
Thank you it works.

About the casing and whether or not fetching the true detail type, it also has an impact on all generated files and UI. In the menus and pages in the event catalog, events start with a capital letter instead of original casing.
